<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $ingredients = [

            // ─── NIGERIAN STAPLES ────────────────────────────────────────────
            ['name' => 'Egusi (Melon Seeds)',            'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Ogiri (Fermented Locust Bean)',  'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Iru (Locust Beans)',             'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Crayfish (Ground)',              'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Dried Stockfish',                'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Dried Catfish',                  'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Ponmo (Cow Skin)',               'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Oxtail',                         'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Goat Meat',                      'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Tripe (Shaki)',                  'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Cow Leg',                        'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Fufu (Cassava)',                 'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Eba (Garri)',                    'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Garri (White)',                  'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Garri (Yellow)',                 'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Pounded Yam',                   'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Amala (Yam Flour)',              'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Tuwo Shinkafa',                 'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Akamu (Pap / Ogi)',             'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Moin Moin Leaves',              'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Efo Riro (Shredded Spinach)',   'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Efo Tete (Green Amaranth)',     'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Bitterleaf (Dried)',            'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Bitterleaf (Fresh)',            'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Uziza Leaves',                  'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Ugu (Fluted Pumpkin Leaves)',   'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Oha Leaves',                    'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Nchanwu (Scent Leaves)',        'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Tatashe (Red Bell Pepper)',     'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Rodo (Scotch Bonnet)',          'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Shombo (Long Red Pepper)',      'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Atarodo (Habanero)',            'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Cameroon Pepper',               'unit' => 'tsp',     'category' => 'Nigerian Staples'],
            ['name' => 'Suya Spice (Yaji)',             'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Nigerian Curry Powder',         'unit' => 'tsp',     'category' => 'Nigerian Staples'],
            ['name' => 'Seasoning Cubes (Maggi)',       'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Seasoning Cubes (Knorr)',       'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Palm Oil',                      'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Groundnut Oil',                 'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Yam (White)',                   'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Cocoyam (Taro)',                'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Plantain (Ripe)',               'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Plantain (Unripe)',             'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Ofada Rice',                    'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Nigerian Beans (Black-eyed)',   'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Brown Beans',                   'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Honey Beans (Oloyin)',          'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Soya Beans',                    'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Tiger Nuts (Aya)',              'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Zobo Leaves (Hibiscus)',        'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Ehuru (African Nutmeg)',        'unit' => 'tsp',     'category' => 'Nigerian Staples'],
            ['name' => 'Ofor (Thickener)',              'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Achi (Thickener)',              'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Ukpaka (Oil Bean Seeds)',       'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Ugba (Shredded Oil Bean)',      'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Agbalumo (African Star Apple)', 'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Elubo (Yam Flour)',             'unit' => 'cups',    'category' => 'Nigerian Staples'],
            ['name' => 'Ogbono (Wild Mango Seeds)',     'unit' => 'tbsp',    'category' => 'Nigerian Staples'],
            ['name' => 'Okra (Fresh)',                  'unit' => 'grams',   'category' => 'Nigerian Staples'],
            ['name' => 'Garden Egg',                    'unit' => 'pieces',  'category' => 'Nigerian Staples'],
            ['name' => 'Corn (Dried)',                  'unit' => 'cups',    'category' => 'Nigerian Staples'],

            // ─── AFRICAN STAPLES ─────────────────────────────────────────────
            ['name' => 'Injera (Ethiopian Flatbread)',  'unit' => 'pieces',  'category' => 'African Staples'],
            ['name' => 'Teff Flour',                    'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Berbere Spice Blend',           'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Niter Kibbeh (Spiced Butter)',  'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Mitmita Spice',                 'unit' => 'tsp',     'category' => 'African Staples'],
            ['name' => 'Fenugreek Seeds',               'unit' => 'tsp',     'category' => 'African Staples'],
            ['name' => 'Ugali (Maize Meal)',            'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Sadza (White Maize Meal)',      'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Mealie Meal',                   'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Cassava (Raw)',                 'unit' => 'grams',   'category' => 'African Staples'],
            ['name' => 'Cassava Flour',                 'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Groundnuts (Peanuts)',          'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Groundnut Paste',               'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Dried Shrimp',                  'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Smoked Fish',                   'unit' => 'grams',   'category' => 'African Staples'],
            ['name' => 'Moringa Powder',                'unit' => 'tsp',     'category' => 'African Staples'],
            ['name' => 'Baobab Powder',                 'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Dawadawa (Fermented Beans)',    'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Peri Peri Sauce',               'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Chakalaka Relish',              'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Ras el Hanout',                 'unit' => 'tsp',     'category' => 'African Staples'],
            ['name' => 'Harissa Paste',                 'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Preserved Lemon',               'unit' => 'pieces',  'category' => 'African Staples'],
            ['name' => 'Argan Oil',                     'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Couscous',                      'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Freekeh',                       'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Dukkah',                        'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Chermoula Marinade',            'unit' => 'tbsp',    'category' => 'African Staples'],
            ['name' => 'Plantain Flour',                'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Millet (Grain)',                'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Sorghum Flour',                 'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'African Yam Bean',              'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Bambara Groundnut',             'unit' => 'cups',    'category' => 'African Staples'],
            ['name' => 'Suya Beef',                     'unit' => 'grams',   'category' => 'African Staples'],

            // ─── PRODUCE ─────────────────────────────────────────────────────
            ['name' => 'Apple',                         'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Asparagus',                     'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Avocado',                       'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Baby Spinach',                  'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Banana',                        'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Beetroot',                      'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Bell Pepper (Green)',           'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Bell Pepper (Red)',             'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Bell Pepper (Yellow)',          'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Bitter Melon',                  'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Blueberries',                   'unit' => 'cups',    'category' => 'Produce'],
            ['name' => 'Breadfruit',                    'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Broccoli',                      'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Cabbage (Green)',               'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Cabbage (Red)',                 'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Carrots',                       'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Cauliflower',                   'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Celery Stalk',                  'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Cherry Tomatoes',               'unit' => 'cups',    'category' => 'Produce'],
            ['name' => 'Chives',                        'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Coconut (Fresh)',               'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Coconut Cream',                 'unit' => 'ml',      'category' => 'Produce'],
            ['name' => 'Coconut Milk',                  'unit' => 'ml',      'category' => 'Produce'],
            ['name' => 'Corn on the Cob',               'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Cucumber',                      'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Eggplant (Aubergine)',          'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Fresh Basil',                   'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Fresh Cilantro',                'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Fresh Dill',                    'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Fresh Mint',                    'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Fresh Parsley',                 'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Fresh Rosemary',                'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Fresh Thyme',                   'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Garlic',                        'unit' => 'cloves',  'category' => 'Produce'],
            ['name' => 'Ginger Root',                   'unit' => 'tbsp',    'category' => 'Produce'],
            ['name' => 'Grapes',                        'unit' => 'cups',    'category' => 'Produce'],
            ['name' => 'Green Beans',                   'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Habanero Pepper',               'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Iceberg Lettuce',               'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Jalapeño Pepper',               'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Kale',                          'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Leek',                          'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Lemon',                         'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Lettuce (Romaine)',             'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Lime',                          'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Mango',                         'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Mushrooms (Button)',            'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Mushrooms (Portobello)',        'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Mushrooms (Shiitake)',          'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Orange',                        'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Pawpaw (Papaya)',               'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Pear',                          'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Peas (Fresh)',                  'unit' => 'cups',    'category' => 'Produce'],
            ['name' => 'Pineapple',                     'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Plum Tomatoes',                 'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Radish',                        'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Red Onion',                     'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Roma Tomato',                   'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Russet Potato',                 'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Spring Onion (Scallion)',       'unit' => 'bunch',   'category' => 'Produce'],
            ['name' => 'Strawberries',                  'unit' => 'cups',    'category' => 'Produce'],
            ['name' => 'Sweet Potato',                  'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Turnip',                        'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Watermelon',                    'unit' => 'grams',   'category' => 'Produce'],
            ['name' => 'Yellow Onion',                  'unit' => 'pieces',  'category' => 'Produce'],
            ['name' => 'Zucchini',                      'unit' => 'pieces',  'category' => 'Produce'],

            // ─── PROTEINS ────────────────────────────────────────────────────
            ['name' => 'Bacon Strips',                  'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Beef Ribs',                     'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Beef Sirloin',                  'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Beef Stew Chunks',              'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Canned Black Beans',            'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Canned Chickpeas',              'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Canned Kidney Beans',           'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Catfish (Fresh)',               'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Chicken Breast (Boneless)',     'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Chicken Drumsticks',            'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Chicken Thighs (Bone-in)',      'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Crab (Whole)',                  'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Croaker Fish (Apo)',            'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Firm Tofu',                     'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Green Lentils',                 'unit' => 'cups',    'category' => 'Proteins'],
            ['name' => 'Ground Beef (80/20)',           'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Lamb Chops',                    'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Lamb Shoulder',                 'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Large Eggs',                    'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Mackerel (Titus Fish)',         'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Pork Belly',                    'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Pork Chops',                    'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Pork Mince',                    'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Prawns',                        'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Quail Eggs',                    'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Red Lentils',                   'unit' => 'cups',    'category' => 'Proteins'],
            ['name' => 'Salmon Fillet',                 'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Sardines (Canned)',             'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Sausages',                      'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Shrimp (Peeled)',               'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Silken Tofu',                   'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Tempeh',                        'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Tilapia Fillet',                'unit' => 'pieces',  'category' => 'Proteins'],
            ['name' => 'Tuna (Canned)',                 'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Turkey Breast',                 'unit' => 'grams',   'category' => 'Proteins'],
            ['name' => 'Whole Chicken',                 'unit' => 'grams',   'category' => 'Proteins'],

            // ─── BAKING, GRAINS & SUGARS ─────────────────────────────────────
            ['name' => 'Active Dry Yeast',              'unit' => 'tsp',     'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Almond Flour',                  'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'All-Purpose Flour',             'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Arborio Rice (Risotto)',        'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Baking Powder',                 'unit' => 'tsp',     'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Baking Soda',                   'unit' => 'tsp',     'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Basmati Rice',                  'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Bread Flour',                   'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Breadcrumbs (Panko)',           'unit' => 'cups',    'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Breadcrumbs (Plain)',           'unit' => 'cups',    'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Brown Rice',                    'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Brown Sugar (Packed)',          'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Caster Sugar',                  'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Cocoa Powder (Unsweetened)',    'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Cornstarch',                    'unit' => 'tbsp',    'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Dark Chocolate Chips',          'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Gelatin Powder',                'unit' => 'tsp',     'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Granulated Sugar',              'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Instant Yeast',                 'unit' => 'tsp',     'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Jasmine Rice',                  'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Oat Flour',                     'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Pasta (Fettuccine)',            'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Pasta (Lasagne Sheets)',        'unit' => 'pieces',  'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Pasta (Penne)',                 'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Pasta (Spaghetti)',             'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Powdered Sugar',                'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Quinoa',                        'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Rice Flour',                    'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Rolled Oats',                   'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Vanilla Extract',               'unit' => 'tsp',     'category' => 'Baking, Grains & Sugars'],
            ['name' => 'White Chocolate Chips',         'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'White Rice',                    'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],
            ['name' => 'Whole Wheat Flour',             'unit' => 'grams',   'category' => 'Baking, Grains & Sugars'],

            // ─── DAIRY & REFRIGERATED ────────────────────────────────────────
            ['name' => 'Buttermilk',                    'unit' => 'ml',      'category' => 'Dairy & Refrigerated'],
            ['name' => 'Condensed Milk (Sweetened)',    'unit' => 'tbsp',    'category' => 'Dairy & Refrigerated'],
            ['name' => 'Cream Cheese',                  'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Cheddar Cheese (Shredded)',     'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Crème Fraîche',                 'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Evaporated Milk',               'unit' => 'ml',      'category' => 'Dairy & Refrigerated'],
            ['name' => 'Feta Cheese',                   'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Gouda Cheese',                  'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Greek Yogurt',                  'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Heavy Cream',                   'unit' => 'ml',      'category' => 'Dairy & Refrigerated'],
            ['name' => 'Mascarpone',                    'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Mozzarella Cheese',             'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Parmesan Cheese (Grated)',      'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Plain Yogurt',                  'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Ricotta Cheese',                'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Salted Butter',                 'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Skimmed Milk',                  'unit' => 'ml',      'category' => 'Dairy & Refrigerated'],
            ['name' => 'Sour Cream',                    'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Unsalted Butter',               'unit' => 'grams',   'category' => 'Dairy & Refrigerated'],
            ['name' => 'Whole Milk',                    'unit' => 'ml',      'category' => 'Dairy & Refrigerated'],

            // ─── OILS, VINEGARS & CONDIMENTS ─────────────────────────────────
            ['name' => 'Apple Cider Vinegar',           'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Avocado Oil',                   'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Balsamic Vinegar',              'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Beef Stock',                    'unit' => 'ml',      'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Chicken Stock',                 'unit' => 'ml',      'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Coconut Oil',                   'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Dark Soy Sauce',                'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Dijon Mustard',                 'unit' => 'tsp',     'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Extra Virgin Olive Oil',        'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Fish Sauce',                    'unit' => 'tsp',     'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Hoisin Sauce',                  'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Honey',                         'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Hot Sauce (Tabasco)',           'unit' => 'tsp',     'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Ketchup',                       'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Maple Syrup',                   'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Mayonnaise',                    'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Olive Oil',                     'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Oyster Sauce',                  'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Peanut Butter',                 'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Rice Wine Vinegar',             'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Sesame Oil',                    'unit' => 'tsp',     'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Soy Sauce',                     'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Sriracha',                      'unit' => 'tsp',     'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Tahini',                        'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Tomato Paste',                  'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Tomato Sauce (Canned)',         'unit' => 'ml',      'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Vegetable Oil',                 'unit' => 'ml',      'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Vegetable Stock',               'unit' => 'ml',      'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'White Wine Vinegar',            'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Worcestershire Sauce',          'unit' => 'tbsp',    'category' => 'Oils, Vinegars & Condiments'],
            ['name' => 'Yellow Mustard',                'unit' => 'tsp',     'category' => 'Oils, Vinegars & Condiments'],

            // ─── PANTRY SPICES & SEASONINGS ──────────────────────────────────
            ['name' => 'Allspice (Ground)',             'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Baking Spice Mix',              'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Bay Leaves',                    'unit' => 'pieces',  'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Black Pepper (Ground)',         'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cardamom (Ground)',             'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cayenne Pepper',                'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Chili Flakes',                  'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Chili Powder',                  'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cinnamon (Ground)',             'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cinnamon Sticks',               'unit' => 'pieces',  'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cloves (Ground)',               'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cloves (Whole)',                'unit' => 'pieces',  'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Coriander (Ground)',            'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cumin (Ground)',                'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Cumin Seeds',                   'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Curry Powder',                  'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Dried Basil',                   'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Dried Oregano',                 'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Dried Rosemary',                'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Dried Thyme',                   'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Garam Masala',                  'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Garlic Powder',                 'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Italian Seasoning',             'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Jerk Seasoning',                'unit' => 'tbsp',    'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Kosher Salt',                   'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Lemon Pepper Seasoning',        'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Mixed Spice',                   'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Mustard Seeds',                 'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Nutmeg (Ground)',               'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Onion Powder',                  'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Saffron',                       'unit' => 'pinch',   'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Sea Salt',                      'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Smoked Paprika',                'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Star Anise',                    'unit' => 'pieces',  'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Sweet Paprika',                 'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'Turmeric (Ground)',             'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],
            ['name' => 'White Pepper (Ground)',         'unit' => 'tsp',     'category' => 'Pantry Spices & Seasonings'],

            // ─── ASIAN PANTRY ─────────────────────────────────────────────────
            ['name' => 'Dashi Stock',                   'unit' => 'ml',      'category' => 'Asian Pantry'],
            ['name' => 'Doenjang (Korean Soy Paste)',   'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Galangal',                      'unit' => 'grams',   'category' => 'Asian Pantry'],
            ['name' => 'Glass Noodles',                 'unit' => 'grams',   'category' => 'Asian Pantry'],
            ['name' => 'Gochujang Paste',               'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Kaffir Lime Leaves',            'unit' => 'pieces',  'category' => 'Asian Pantry'],
            ['name' => 'Lemongrass Stalk',              'unit' => 'pieces',  'category' => 'Asian Pantry'],
            ['name' => 'Mirin',                         'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Miso Paste (Red)',              'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Miso Paste (White)',            'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Nori Sheets',                   'unit' => 'pieces',  'category' => 'Asian Pantry'],
            ['name' => 'Ramen Noodles',                 'unit' => 'grams',   'category' => 'Asian Pantry'],
            ['name' => 'Rice Noodles',                  'unit' => 'grams',   'category' => 'Asian Pantry'],
            ['name' => 'Rice Wine (Sake)',              'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Sambal Oelek',                  'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Spring Roll Wrappers',          'unit' => 'pieces',  'category' => 'Asian Pantry'],
            ['name' => 'Sushi Rice',                    'unit' => 'grams',   'category' => 'Asian Pantry'],
            ['name' => 'Tamarind Paste',                'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Thai Basil',                    'unit' => 'bunch',   'category' => 'Asian Pantry'],
            ['name' => 'Thai Green Curry Paste',        'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Thai Red Curry Paste',          'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Toasted Sesame Seeds',          'unit' => 'tbsp',    'category' => 'Asian Pantry'],
            ['name' => 'Udon Noodles',                  'unit' => 'grams',   'category' => 'Asian Pantry'],
            ['name' => 'Wonton Wrappers',               'unit' => 'pieces',  'category' => 'Asian Pantry'],
        ];

        // Add timestamps
        $rows = array_map(fn($i) => array_merge($i, [
            'created_at' => $now,
            'updated_at' => $now,
        ]), $ingredients);

        // Insert in chunks to avoid query size limits
        foreach (array_chunk($rows, 50) as $chunk) {
            DB::table('ingredients')->insert($chunk);
        }

        $this->command->info('✅ ' . count($ingredients) . ' ingredients seeded successfully!');
    }
}